### ISSUE TITLE
NEST 6.0 Beta: Setting BulkRequest timeout w/ a TimeSpan causes 400 BadRequest

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2970]
I'm creating a `BulkRequest` w/ a call like the following:
```
private static BulkRequest CreateBulkRequest(int size)
{
   return new BulkRequest
   {
      Refresh = Refresh.True,
      Timeout = TimeSpan.FromSeconds(size),
      Operations = new List<IBulkOperation>()
   };
}
```
When I make the request w/ a `size` = 1000 (ie. I'm indexing\updating 1000 items at a time and adjust the timeout based on the size), the ES 6.0 server responds:
`Type: parse_exception Reason: \"failed to parse [16.67m], fractional time values are not supported\" CausedBy: \"Type: number_format_exception Reason: \"For input string: \"16.67\"\"\"`

Request: `POST: /_bulk?pretty=true&refresh=true&timeout=16.67m`

I verified that the NEST `Time` has a constructor which takes a `TimeSpan` so why does it format the request timeout in a format that is not supported?  Is this a bug or am I doing something wrong?

**Comment by russcam** [comment]
@tdoman I think this is related to #2818 and https://github.com/elastic/elasticsearch-net/commit/c192964c776063a04a3987dffbe8ed7381e1eba1.

I'll be looking at this again today.

**Comment by tdoman** [comment]
Cool, thanks @russcam!

**Comment by russcam** [comment]
@tdoman this should be fixed in 6.0.0-beta1 and later if you'd like to give it a spin?

**Comment by tdoman** [comment]
@russcam Oh great, I've been using 6.0.0-beta1 but didn't know it had been addressed in that build.  Thanks, I'll give it a spin.

**Comment by tdoman** [comment]
@russcam I'm still seeing the same issue as I described originally in 6.0.0-beta1.  Is there a beta2 build perhaps?

**Comment by russcam** [comment]
My apologies @tdoman for sending you on a wild goose chase! The change for the master branch is in https://github.com/elastic/elasticsearch-net/pull/3026 so will be there once this is merged (the change is already in 5.x branch, which is where my confusion was).

**Comment by tdoman** [comment]
@russcam No worries, do you know if there's there going to be a beta2 or is the next step GA?

**Comment by Mpdreamz** [comment]
fixed with #3026

**Comment by Mpdreamz** [comment]
@tdoman there is already an `rc1` out so the next step would be `rc2` however we are hoping to go to GA this week.

**Comment by tdoman** [comment]
@Mpdreamz fantastic, looking forward to the GA!  Meanwhile, I don't see an `rc1` on MyGet or NuGet, is it published somewhere?  Anyway, I'd be happy to try out an `rc2` in my dev systems if you create one before GA.
